"""modif

Revision ID: 247f2ac9ed2b
Revises: 70e42771895c
Create Date: 2025-09-28 09:36:00.460212

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '247f2ac9ed2b'
down_revision: Union[str, Sequence[str], None] = '70e42771895c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profil',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('badges', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('competences', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('objectifs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motivation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('energie', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profil_utilisateur_id'), 'profil', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profil_utilisateur_id'), table_name='profil')
    op.drop_table('profil')
    # ### end Alembic commands ###
