"""init

Revision ID: 896f6098d11e
Revises: 
Create Date: 2025-09-27 20:03:52.323223

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '896f6098d11e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motDePasseHash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ETUDIANT', 'PROFESSEUR', name='statututilisateur'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('etudiant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('niveau_technique', sa.Integer(), nullable=False),
    sa.Column('competences', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('objectifs_apprentissage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motivation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('niveau_energie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professeur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('niveau_experience', sa.Integer(), nullable=False),
    sa.Column('specialites', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('motivation_principale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('niveau_technologique', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professeur')
    op.drop_table('etudiant')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
