"""modif

Revision ID: b7606e665139
Revises: 247f2ac9ed2b
Create Date: 2025-09-28 13:39:34.363770

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7606e665139'
down_revision: Union[str, Sequence[str], None] = '247f2ac9ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profil_utilisateur_id'), table_name='profil')
    op.drop_table('profil')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profil',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('niveau', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('badges', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('competences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('objectifs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('motivation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('energie', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name=op.f('profil_utilisateur_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profil_pkey'))
    )
    op.create_index(op.f('ix_profil_utilisateur_id'), 'profil', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###
